version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: wreath
      POSTGRES_PASSWORD: wreath
      POSTGRES_DB: wreath
    ports:
      - "5432:5432"
    volumes:
      - wreath_db_data:/var/lib/postgresql/data

volumes:
  wreath_db_data:
